Repository atlp-rwanda/e-commerce-bitcrafters-fn, pull requests merged in 2024-06, with the labels that each got.

#2 [#187364666] Set up React project with Vite, Babel, Airbnb ESLint and PR template
  .babelrc
  .env.example
  .eslintrc.js
  .github/pull_request_template.md
  .gitignore
  index.html
  package-lock.json
  package.json
  public/vite.svg
  src/App.css
  src/assets/react.svg
  src/components/App.tsx
  src/index.css
  src/main.tsx
  src/vite-env.d.ts
  tsconfig.json
  tsconfig.node.json
  vite.config.ts
Labels: Ready for peer review

#1 [#187364668] Setting up redux
  package-lock.json
  package.json
  src/App.tsx
  src/components/App.tsx
  src/components/counter.tsx
  src/main.tsx
  src/redux/counter.tsx
  src/redux/store.tsx
Labels: Ready to be merged

#7 [#187364672]chore(setup): set sass and tailwind in vite
  package-lock.json
  package.json
  postcss.config.js
  src/App.css
  src/App.tsx
  src/app.scss
  src/index.css
  tailwind.config.js
Labels: Ready to be merged

#4 [#187364671] chore: setup react router dom
  package-lock.json
  package.json
  src/App.tsx
  src/app.scss
  src/components/Footer.tsx
  src/components/Layout.tsx
  src/components/Navbar.tsx
  src/routes/index.tsx
  src/views/Home.tsx
  src/views/Login.tsx
  tsconfig.json
Labels: Ready to be merged

#5 #[187364670] - Chore(Jest Testing): Adding a testing mechanism with Jest library
  .eslintrc.js
  .gitignore
  babel.config.js
  jest.config.cjs
  package-lock.json
  package.json
  src/components/Hello.tsx
  src/jest.setup.ts
  src/test/App.test.tsx
  src/test/__mocks__/fileMock.js
  tsconfig.jest.json
  tsconfig.json
Labels: Ready to be merged, Changes requested

#10 [#187364673] Chore: Adding client README file
  README.md
  public/andela.png
Labels: Ready to be merged

#8 [#187364675] Configure ESLint and Git Precommit hook to run tests
  .babelrc
  .eslintrc.js
  .husky/pre-commit
  .prettierrc
  babel.config.js
  eslint.config.js
  package-lock.json
  package.json
  postcss.config.js
  src/components/counter.tsx
  src/main.tsx
  src/redux/counter.tsx
  tailwind.config.js
  tsconfig.json
Labels: Ready to be merged

#9 [#187364677] - Chore(Storybook): Configuring storybook for component development
  .gitignore
  .storybook/main.ts
  .storybook/preview.ts
  jest.config.cjs
  package-lock.json
  package.json
  src/components/Button.tsx
  src/stories/Button.stories.tsx
  tsconfig.json
Labels: Ready to be merged

#6 [#187364676] -chore: setup GitHub actions to run tests
  .github/workflows/ci.yml
  jest.config.cjs
  package-lock.json
  src/App.tsx
  src/components/Button.tsx
  src/components/counter.tsx
  src/main.tsx
  src/test/App.test.tsx
  src/test/jest.setup.ts
  src/views/Login.tsx
Labels: Ready to be merged

#3 [#187364674]chore(setup): set code climate and test coverage
  .circleci/config.yml
  .codeclimate.yml
  README.md
Labels: Ready to be merged

#13 [#187814639] - Chore(Layout): Making layout design of the website
  index.html
  package-lock.json
  package.json
  src/app.scss
  src/assets/images/Bit.Shop-white.svg
  src/assets/images/Bit.Shop.svg
  src/assets/images/black-lady.svg
  src/assets/images/star.svg
  src/assets/images/women-signup.svg
  src/components/Footer.tsx
  src/components/Navbar.tsx
  src/index.css
  src/test/App.test.tsx
  src/test/Navbar.test.tsx
  src/test/__snapshots__/Navbar.test.tsx.snap
  src/views/Home.tsx
  tailwind.config.js
Labels: Ready to be merged

#20 fix: fix routing errors on netlify
  netlify.toml
Labels: Ready to be merged

#19 [#187364680] - Feature(Login): Users should be able to Login with Email and Password
  babel.config.cjs
  index.html
  package-lock.json
  package.json
  src/components/Button.tsx
  src/components/Navbar.tsx
  src/components/TextInput.tsx
  src/hooks/AxiosInstance.tsx
  src/redux/authSlice.tsx
  src/redux/store.tsx
  src/stories/Button.stories.tsx
  src/test/App.test.tsx
  src/test/Navbar.test.tsx
  src/test/__mocks__/axios.tsx
  src/test/__snapshots__/Navbar.test.tsx.snap
  src/test/authSlice.test.tsx
  src/test/components/TextInput.test.tsx
  src/test/services/AxiosInstance.test.tsx
  src/test/views/Login.test.tsx
  src/views/Login.tsx
  src/vite-env.d.ts
  tsconfig.json
  vite.config.ts
Labels: Ready to be merged

#21 Feature(Change Password): User should be prompted to change their passwords every x amount of time.
  src/components/Navbar.tsx
  src/components/TextInput.tsx
  src/routes/index.tsx
  src/test/views/Login.test.tsx
  src/test/views/ResquestPasswordChange.test.tsx
  src/test/views/changePassword.test.tsx
  src/views/ChangePassword.tsx
  src/views/Login.tsx
  src/views/RequestPasswordChange.tsx
Labels: Ready to be merged

#15 [#187364683] feature-two factor authentintication for sellers
  package-lock.json
  package.json
  src/App.tsx
  src/routes/index.tsx
  src/test/views/SendOtp.test.tsx
  src/test/views/TwoFactorAuth.test.tsx
  src/views/Login.tsx
  src/views/TwoFactorAuth.tsx
Labels: Ready to be merged

#18 [#187364678] Feature: User registration and send email verification
  jest.config.cjs
  package-lock.json
  package.json
  public/bg0.svg
  public/invalid.svg
  public/verified.svg
  src/api/auth.ts
  src/api/axiosInstance.ts
  src/hooks/AxiosInstance.tsx
  src/main.tsx
  src/redux/store.tsx
  src/redux/userSlice.tsx
  src/routes/index.tsx
  src/test/authaxios.test.ts
  src/test/emailVerified.test.tsx
  src/test/invalidToken.test.tsx
  src/test/signup.test.tsx
  src/test/userSlice.test.ts
  src/test/verifyEmail.test.tsx
  src/views/Login.tsx
  src/views/emailVerified.tsx
  src/views/invalidToken.tsx
  src/views/signup.tsx
  src/views/verifyEmail.tsx
  tailwind.config.js
Labels: Ready to be merged

#17 [#187364682] ft-Users should be presented with a reset password link
  package-lock.json
  package.json
  src/routes/index.tsx
  src/test/ForgotPassword.test.tsx
  src/test/TextInput.test.tsx
  src/views/ForgotPassword.tsx
  src/views/Login.tsx
  tailwind.config.js
Labels: Ready to be merged

#25 Fixing: Delete duplicated file
  src/api/axiosInstance.ts
Labels: Ready to be merged

#14 [#187364679]User should be able to login via google
  .codeclimate.yml
  eslint.config.js
  package-lock.json
  package.json
  src/test/views/Login.test.tsx
  src/test/views/TwoFactorAuth.test.tsx
  src/views/Home.tsx
  src/views/Login.tsx
  src/views/TwoFactorAuth.tsx
  tsconfig.json
Labels: Ready to be merged
