Repository atlp-rwanda/e-commerce-bitcrafters-fn, pull requests merged in 2024-07, with the labels that each got.

#24 [187364690]:admin should be to view all accounts and set permissions or roles
  package-lock.json
  package.json
  src/App.tsx
  src/assets/images/profileImage.svg
  src/components/DashBoardButton.tsx
  src/components/ProtectedRoute.tsx
  src/components/RoleChange.tsx
  src/components/SideNav.tsx
  src/layouts/DashLayout.tsx
  src/layouts/Layout.tsx
  src/redux/authSlice.tsx
  src/redux/store.tsx
  src/routes/index.tsx
  src/test/DashLayout.test.tsx
  src/test/authSlice.test.tsx
  src/test/components/DasboardButton.test.tsx
  src/test/components/ProtectedRoute.test.tsx
  src/test/views/Login.test.tsx
  src/test/views/admin/DashBoardStats.test.tsx
  src/test/views/admin/SideNav.test.tsx
  src/test/views/admin/UserTable.test.tsx
  src/views/Login.tsx
  src/views/admin/DashboardStats.tsx
  src/views/admin/UsersTable.tsx
  tailwind.config.js
Labels: Ready to be merged

#22 [187364689] Users should be able to view and edit their profiles
  package-lock.json
  src/components/Logout.tsx
  src/components/Navbar.tsx
  src/components/SectionHeader.tsx
  src/routes/index.tsx
  src/test/Logout.test.tsx
  src/test/UserProfie.test.tsx
  src/views/UserProfile.tsx
  tailwind.config.js
Labels: Ready to be merged

#16 [#187364686] A seller should be able to create/add items
  package-lock.json
  package.json
  src/components/Button.tsx
  src/components/ProtectedRoute.tsx
  src/layouts/SellerLayout.tsx
  src/redux/store.tsx
  src/routes/index.tsx
  src/test/views/AddProduct.test.tsx
  src/test/views/CreateCollection.test.tsx
  src/test/views/SelectCollection.test.tsx
  src/views/Login.tsx
  src/views/TwoFactorAuth.tsx
  src/views/seller/AddProductForm.tsx
  src/views/seller/CreateColletion.tsx
  src/views/seller/SelectCollection.tsx
  tailwind.config.js
Labels: Ready to be merged

#32 [#187364693] - Feature(User search): Adding a search feature for users to use
  src/components/Navbar.tsx
  src/components/SearchComponent.tsx
  src/routes/index.tsx
  src/test/components/SearchComponent.test.tsx
  src/views/SingleProduct.tsx
  src/views/UserProfile.tsx
Labels: Ready to be merged

#34 [#187364694]:Users should be able to chat
  package-lock.json
  package.json
  src/components/ProtectedRoute.tsx
  src/redux/authSlice.tsx
  src/redux/store.tsx
  src/test/Home.test.tsx
  src/test/authSlice.test.tsx
  src/test/views/LoginNavigation.test.tsx
  src/test/views/SendOtp.test.tsx
  src/test/views/TwoFactorAuth.test.tsx
  src/test/views/admin/UserTable.test.tsx
  src/test/views/chat/chat.test.tsx
  src/views/Home.tsx
  src/views/Login.tsx
  src/views/TwoFactorAuth.tsx
  src/views/chat/Chat.tsx
  tailwind.config.js
Labels: Ready to be merged

#31 [#187364691] ft-Admin should be able to disable an account for various reasons
  src/components/StatusChangeModal.tsx
  src/test/components/StatusCHangeModel.test.tsx
  src/test/views/admin/UserTable.test.tsx
  src/views/ForgotPassword.tsx
  src/views/admin/UsersTable.tsx
  tailwind.config.js
Labels: Ready to be merged

#33 [#187364697] Feature: users should see a toast for new notifications
  jest.config.cjs
  package-lock.json
  package.json
  src/App.tsx
  src/components/Navbar.tsx
  src/components/ProtectedRoute.tsx
  src/components/SideNav.tsx
  src/components/notificationtoast.tsx
  src/routes/index.tsx
  src/test/jest.setup.ts
  src/test/notificationtoast.test.tsx
  src/test/views/admin/SideNav.test.tsx
  src/views/Login.tsx
  tsconfig.json
Labels: Ready to be merged

#35 [#187364696] Implement notifications pane
  .codeclimate.yml
  package-lock.json
  package.json
  src/components/Navbar.tsx
  src/components/SideNav.tsx
  src/routes/index.tsx
  src/test/views/NotificationPane.test.tsx
  src/test/views/admin/SideNav.test.tsx
  src/views/NotificationPane.tsx
  tailwind.config.js
Labels: Ready to be merged

#26 Chore(Layout): Making layout design of the website
  package-lock.json
  src/app.scss
  src/assets/images/Image2.svg
  src/assets/images/Image3.svg
  src/assets/images/furniture.svg
  src/assets/images/image.svg
  src/assets/images/macbook.svg
  src/assets/images/person1.svg
  src/assets/images/person2.svg
  src/components/Button.tsx
  src/components/CollectionCard.tsx
  src/components/MainProductCard.tsx
  src/components/Navbar.tsx
  src/components/ServiceCard.tsx
  src/components/TeamCard.tsx
  src/components/servicesSection.tsx
  src/routes/index.tsx
  src/test/views/AboutPage.spec.tsx
  src/test/views/Home.spec.tsx
  src/views/AboutPage.tsx
  src/views/ErroPage.tsx
  src/views/Home.tsx
Labels: Ready to be merged

#29 [#187364685] Seller can view all products and a single product
  package-lock.json
  package.json
  src/components/SellerSideNav.tsx
  src/layouts/SellerDashLayout.tsx
  src/routes/index.tsx
  src/test/components/SellerSideNav.test.tsx
  src/test/views/TwoFactorAuth.test.tsx
  src/test/views/seller/SellerDashboardStats.test.tsx
  src/test/views/seller/viewProduct.test.tsx
  src/test/views/seller/viewSingleProduct.test.tsx
  src/views/Login.tsx
  src/views/NotificationPane.tsx
  src/views/TwoFactorAuth.tsx
  src/views/dashboard/sellerDashboardStats.tsx
  src/views/seller/viewProduct.tsx
  src/views/seller/viewSingleProduct.tsx
Labels: Ready to be merged

#36 [187364699] - Feature(User Cart): A buyer should be able to view their cart
  package-lock.json
  package.json
  src/components/CartProductCard.tsx
  src/components/Navbar.tsx
  src/components/SearchComponent.tsx
  src/redux/cart.tsx
  src/redux/store.tsx
  src/routes/index.tsx
  src/test/Navbar.test.tsx
  src/test/redux/cart.test.tsx
  src/test/views/UserCart.test.tsx
  src/test/views/checkout.text.tsx
  src/views/CheckoutPage.tsx
  src/views/Login.tsx
  src/views/UserCart.tsx
Labels: Ready to be merged

#42 [#187364710] Marking all notifications as read
  jest.config.cjs
  package-lock.json
  src/assets/images/no-notification.jpg
  src/redux/notificationSlice.tsx
  src/redux/store.tsx
  src/test/redux/notification.test.tsx
  src/test/views/NotificationPane.test.tsx
  src/views/NotificationPane.tsx
Labels: Ready to be merged

#27 [#187364688] Feature: Seller should be able to delete product from their collection
  src/routes/index.tsx
  src/test/views/seller/viewProduct.test.tsx
  src/views/seller/viewProduct.tsx
Labels: Ready to be merged

#39 [#187364703] ft-A buyer should be able to checkout
  jest.config.cjs
  package-lock.json
  package.json
  src/app.scss
  src/components/CheckoutSubmit.tsx
  src/routes/index.tsx
  src/test/Checkout.test.tsx
  src/test/components/CheckoutSubmit.test.tsx
  src/test/views/checkout.text.tsx
  src/views/CheckoutPage.tsx
  src/views/XCreditCard.tsx
  src/views/XMobileMoney.tsx
  src/views/checkout.tsx
  tailwind.config.js
Labels: Ready to be merged

#45 [#187364701]- A buyer should be able to update their cart
  package.json
  src/components/CartProductCard.tsx
  src/components/UpdateCartModal.tsx
  src/test/components/UpdateCartModal.test.tsx
  src/test/views/UserCart.test.tsx
  src/views/UserCart.tsx
Labels: Ready for peer review

#30 [#187364687] A seller should be able to update a product
  package-lock.json
  src/routes/index.tsx
  src/test/views/seller/UpdateProduct.test.tsx
  src/views/seller/UpdateProductForm.tsx
  src/views/seller/viewProduct.tsx
Labels: Ready to be merged

#46 [#187364700] A buyer should be able to clear their cart
  src/test/views/UserCart.test.tsx
  src/views/UserCart.tsx
Labels: Ready to be merged

#41 [#187364698] User should add product to cart
  package-lock.json
  src/components/MainProductCard.tsx
  src/components/Navbar.tsx
  src/test/components/MainProductCard.test.tsx
  src/test/redux/cart.test.tsx
  src/test/views/Home.spec.tsx
  src/test/views/seller/viewSingleProduct.test.tsx
  src/views/Home.tsx
  src/views/seller/viewSingleProduct.tsx
Labels: Ready to be merged

#43 [#187364704] Feature: Make payment using stripe
  package-lock.json
  package.json
  src/components/CheckoutSubmit.tsx
  src/components/Confirmation.tsx
  src/components/StripePayment.tsx
  src/constants.tsx
  src/routes/index.tsx
  src/test/components/CheckoutSubmit.test.tsx
  src/test/components/PaymentConfirmation.test.tsx
  src/test/components/StripePayment.test.tsx
  src/views/checkout.tsx
Labels: Ready to be merged

#48 Feature(User Order Track): A buyer should be able to track an order
  .hintrc
  package-lock.json
  package.json
  src/components/MainProductCard.tsx
  src/components/Navbar.tsx
  src/routes/index.tsx
  src/test/views/UserOrderTrack.test.tsx
  src/test/views/UserOrders.test.tsx
  src/views/UserOrderTrack.tsx
  src/views/UserOrders.tsx
  tailwind.config.js
Labels: Ready to be merged

#49 [#187364731] Feature: Protected routes should be used by authenticated users
  src/components/LoSiNavbar.tsx
  src/components/MainProductCard.tsx
  src/components/Navbar.tsx
  src/components/PublicRoute.tsx
  src/layouts/Layout.tsx
  src/routes/index.tsx
  src/test/LoSiNavbar.test.tsx
  src/test/Navbar.test.tsx
  src/test/__snapshots__/LoSiNavbar.test.tsx.snap
  src/test/components/MainProductCard.test.tsx
  src/test/components/PublicRoute.test.tsx
  src/test/components/__snapshots__/PublicRoute.test.tsx.snap
  src/views/Login.tsx
Labels: Ready to be merged

#57 Fix: handle issues on wishlist, update product and authentication
  src/components/Navbar.tsx
  src/redux/userSlice.tsx
  src/views/Login.tsx
  src/views/seller/UpdateProductForm.tsx
  src/views/seller/viewSingleProduct.tsx
  src/views/signup.tsx
Labels: Ready to be merged

#50 [187364706] A buyer should see recommended products
  package-lock.json
  src/test/views/Home.spec.tsx
  src/test/views/seller/viewSingleProduct.test.tsx
  src/views/Home.tsx
  src/views/seller/viewSingleProduct.tsx
Labels: Ready to be merged

#56 Fix: Making fixes on routes
  package-lock.json
  package.json
  src/components/ImageCaursel.tsx
  src/components/LoSiNavbar.tsx
  src/components/MainProductCard.tsx
  src/components/Navbar.tsx
  src/components/SearchComponent.tsx
  src/hooks/AxiosInstance.tsx
  src/test/components/MainProductCard.test.tsx
  src/test/components/SearchComponent.test.tsx
  src/test/hooks/AxiosInstance.test.tsx
  src/test/views/Home.spec.tsx
  src/test/views/UserOrderTrack.test.tsx
  src/views/Home.tsx
  src/views/seller/viewSingleProduct.tsx
Labels: Ready for peer review, Need Rebase

#55 Fix: Protect routes & Adding dashboard icon on navbar
  package-lock.json
  src/components/MainProductCard.tsx
  src/components/Navbar.tsx
  src/components/SellerSideNav.tsx
  src/components/SideNav.tsx
  src/routes/index.tsx
  src/test/Navbar.test.tsx
  src/views/Login.tsx
  src/views/seller/viewSingleProduct.tsx
Labels: Ready to be merged

#59 Fix: handle some raised issues
  src/components/Navbar.tsx
  src/components/SellerSideNav.tsx
  src/components/SideNav.tsx
  src/routes/index.tsx
  src/test/UserProfie.test.tsx
  src/test/components/SellerSideNav.test.tsx
  src/test/views/admin/SideNav.test.tsx
  src/test/views/seller/viewSingleProduct.test.tsx
  src/views/UserProfile.tsx
  src/views/seller/SelectCollection.tsx
  src/views/seller/viewSingleProduct.tsx
Labels: Ready to be merged

#60 Fix: Adding payment with mobile money
  package-lock.json
  src/components/CheckoutSubmit.tsx
  src/components/Logout.tsx
  src/components/Navbar.tsx
  src/components/SideNav.tsx
  src/routes/index.tsx
  src/test/Logout.test.tsx
  src/test/Navbar.test.tsx
  src/test/components/CheckoutSubmit.test.tsx
  src/test/views/MobilePayment.test.tsx
  src/test/views/seller/viewSingleProduct.test.tsx
  src/views/PaymentSuccess.tsx
  src/views/SingleProduct.tsx
  src/views/UserCart.tsx
  src/views/UserOrderTrack.tsx
  src/views/UserOrders.tsx
  src/views/XMobileMoney.tsx
Labels: Ready for peer review

#65 Fix: Removing private env variable
  jest.config.cjs
  package-lock.json
  package.json
  src/components/notificationtoast.tsx
Labels: Ready to be merged

#66 [#187946524] Feature: Seller should see stats
  package-lock.json
  package.json
  src/components/Confirmation.tsx
  src/components/SellerSideNav.tsx
  src/components/SellerStats.tsx
  src/layouts/SellerDashLayout.tsx
  src/routes/index.tsx
  src/test/components/SellerSideNav.test.tsx
  src/test/components/SellerStats.test.tsx
  src/test/views/seller/SellerDashboardStats.test.tsx
  src/views/dashboard/sellerDashboardStats.tsx
  tailwind.config.js
Labels: Ready to be merged

#67 Fix: seller able to view unavalaible products
  src/views/seller/viewSingleProduct.tsx
Labels: Ready to be merged

#68 Fixing payment for insufficient funds
  src/components/StripePayment.tsx
Labels: Ready to be merged
